version: 1.0.74-apha-{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
clone_folder: c:\projects\infusion
init:
- cmd: git config --global core.autocrlf true
install:
- cmd: >-
    git submodule update --init --recursive

    nuget restore
build_script:
- cmd: msbuild "c:\projects\infusion\Infusion.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:OtherDefineConstants=SLOW_MACHINE
test_script:
- cmd: >-
    dotnet test "c:\projects\infusion\Infusion.Tests\Infusion.Tests.csproj" -v=normal --configuration Release --no-build /property:Platform=AnyCPU

    dotnet test "c:\projects\infusion\Infusion.Proxy.Tests\Infusion.Proxy.Tests.csproj" -v=normal --configuration Release --no-build /property:Platform=AnyCPU

    dotnet test "c:\projects\infusion\InjectionScript\src\InjectionScript.Tests\InjectionScript.Tests.csproj" -v=normal --configuration Release --no-build /property:Platform=AnyCPU

    dotnet test "c:\projects\infusion\Infusion.Desktop.Tests\Infusion.Desktop.Tests.csproj" -v=normal --configuration Release --no-build /property:Platform=AnyCPU

    dotnet test "c:\projects\infusion\Infusion.LegacyApi.Tests\Infusion.LegacyApi.Tests.csproj" -v=normal --configuration Release --no-build /property:Platform=AnyCPU